version: 0.2

env:
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Downloading and installing Gradle 7.4..."
      - wget https://services.gradle.org/distributions/gradle-7.4-bin.zip
      - unzip gradle-7.4-bin.zip
      - export GRADLE_HOME=$PWD/gradle-7.4
      - export PATH=$GRADLE_HOME/bin:$PATH
      - echo "Using Gradle from \$GRADLE_HOME"
      - gradle -v
  pre_build:
    commands:
      - echo "Pre-build phase..."
      - echo "Cleaning the project..."
      - gradle clean
  build:
    commands:
      - echo "Build phase..."
      - echo "Building the project..."
      - gradle build
      - echo "Building WAR file..."
      - gradle bootWar
  post_build:
    commands:
      - echo "Post-build phase..."
      - echo "Build completed successfully."

artifacts:
  files:
    - build/libs/*.war
  discard-paths: yes

cache:
  paths:
    - /root/.gradle/caches/
    - /root/.gradle/wrapper/
